/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/
/// <reference types="react" />
declare const AlertMainExample: () => JSX.Element;
export { AlertMainExample };
declare const AlertInlineExample: () => JSX.Element;
export { AlertInlineExample };
declare const AlertInformationalExample: () => JSX.Element;
export { AlertInformationalExample };
declare const AlertPositiveExample: () => JSX.Element;
export { AlertPositiveExample };
declare const AlertNegativeExample: () => JSX.Element;
export { AlertNegativeExample };
declare const AlertStickyExample: () => JSX.Element;
export { AlertStickyExample };
declare const AlertWarningExample: () => JSX.Element;
export { AlertWarningExample };
declare const AvatarMainExample: () => JSX.Element;
export { AvatarMainExample };
declare const AvatarGroupExample: () => JSX.Element;
export { AvatarGroupExample };
declare const AvatarGroupAnimatedExample: () => JSX.Element;
export { AvatarGroupAnimatedExample };
declare const AvatarGroupOverflowExample: () => JSX.Element;
export { AvatarGroupOverflowExample };
declare const AvatarGroupOverflowTooltipExample: () => JSX.Element;
export { AvatarGroupOverflowTooltipExample };
declare const AvatarGroupStackedExample: () => JSX.Element;
export { AvatarGroupStackedExample };
declare const AvatarIconExample: () => JSX.Element;
export { AvatarIconExample };
declare const AvatarInitialsExample: () => JSX.Element;
export { AvatarInitialsExample };
declare const AvatarPictureExample: () => JSX.Element;
export { AvatarPictureExample };
declare const AvatarSizesExample: () => JSX.Element;
export { AvatarSizesExample };
declare const AvatarStatusesExample: () => JSX.Element;
export { AvatarStatusesExample };
declare const AnchorMainExample: () => JSX.Element;
export { AnchorMainExample };
declare const AnchorAsButtonExample: () => JSX.Element;
export { AnchorAsButtonExample };
declare const BadgeMainExample: () => JSX.Element;
export { BadgeMainExample };
declare const BadgeSoftExample: () => JSX.Element;
export { BadgeSoftExample };
declare const BadgeStatusesExample: () => JSX.Element;
export { BadgeStatusesExample };
declare const BlockquoteFooterExample: () => JSX.Element;
export { BlockquoteFooterExample };
declare const BlockquoteMainExample: () => JSX.Element;
export { BlockquoteMainExample };
declare const BreadcrumbsButtonExample: () => JSX.Element;
export { BreadcrumbsButtonExample };
declare const BreadcrumbsExtremeTruncationExample: () => JSX.Element;
export { BreadcrumbsExtremeTruncationExample };
declare const BreadcrumbsFolderExample: () => JSX.Element;
export { BreadcrumbsFolderExample };
declare const BreadcrumbsLinkExample: () => JSX.Element;
export { BreadcrumbsLinkExample };
declare const BreadcrumbsMainExample: () => JSX.Element;
export { BreadcrumbsMainExample };
declare const BreadcrumbsTruncationExample: () => JSX.Element;
export { BreadcrumbsTruncationExample };
declare const BreadcrumbsCustomOverflowDropdownExample: () => JSX.Element;
export { BreadcrumbsCustomOverflowDropdownExample };
declare const ButtonSizeExample: () => JSX.Element;
export { ButtonSizeExample };
declare const ButtonDefaultExample: () => JSX.Element;
export { ButtonDefaultExample };
declare const ButtonHighVisibilityExample: () => JSX.Element;
export { ButtonHighVisibilityExample };
declare const ButtonBorderlessExample: () => JSX.Element;
export { ButtonBorderlessExample };
declare const ButtonCTAExample: () => JSX.Element;
export { ButtonCTAExample };
declare const ButtonMainExample: () => JSX.Element;
export { ButtonMainExample };
declare const IconButtonMainExample: () => JSX.Element;
export { IconButtonMainExample };
declare const IdeasButtonMainExample: () => JSX.Element;
export { IdeasButtonMainExample };
declare const SplitButtonMainExample: () => JSX.Element;
export { SplitButtonMainExample };
declare const ButtonGroupMainExample: () => JSX.Element;
export { ButtonGroupMainExample };
declare const ButtonGroupVerticalExample: () => JSX.Element;
export { ButtonGroupVerticalExample };
declare const ButtonGroupOverflowExample: () => JSX.Element;
export { ButtonGroupOverflowExample };
declare const ButtonGroupInputExample: () => JSX.Element;
export { ButtonGroupInputExample };
declare const ButtonGroupUsageExample: () => JSX.Element;
export { ButtonGroupUsageExample };
declare const CarouselMainExample: () => JSX.Element;
export { CarouselMainExample };
declare const CarouselControlledExample: () => JSX.Element;
export { CarouselControlledExample };
declare const CarouselOnlyDotsExample: () => JSX.Element;
export { CarouselOnlyDotsExample };
declare const CheckboxMainExample: () => JSX.Element;
export { CheckboxMainExample };
declare const CheckboxIndeterminateExample: () => JSX.Element;
export { CheckboxIndeterminateExample };
declare const CheckboxLoadingExample: () => JSX.Element;
export { CheckboxLoadingExample };
declare const CheckboxStatusesExample: () => JSX.Element;
export { CheckboxStatusesExample };
declare const CheckboxVisibilityExample: () => JSX.Element;
export { CheckboxVisibilityExample };
declare const CheckboxInputGroupExample: () => JSX.Element;
export { CheckboxInputGroupExample };
declare const CodeMainExample: () => JSX.Element;
export { CodeMainExample };
declare const ColorPickerMainExample: () => JSX.Element;
export { ColorPickerMainExample };
declare const ColorPickerBasicExample: () => JSX.Element;
export { ColorPickerBasicExample };
declare const ColorPickerAdvancedExample: () => JSX.Element;
export { ColorPickerAdvancedExample };
declare const ColorPickerAdvancedPopoverExample: () => JSX.Element;
export { ColorPickerAdvancedPopoverExample };
declare const ComboBoxMainExample: () => JSX.Element;
export { ComboBoxMainExample };
declare const ComboBoxControlledExample: () => JSX.Element;
export { ComboBoxControlledExample };
declare const ComboBoxCustomExample: () => JSX.Element;
export { ComboBoxCustomExample };
declare const ComboBoxDisabledExample: () => JSX.Element;
export { ComboBoxDisabledExample };
declare const ComboBoxLabelExample: () => JSX.Element;
export { ComboBoxLabelExample };
declare const ComboBoxLoadingExample: () => JSX.Element;
export { ComboBoxLoadingExample };
declare const ComboBoxMessageExample: () => JSX.Element;
export { ComboBoxMessageExample };
declare const ComboBoxMessageIconExample: () => JSX.Element;
export { ComboBoxMessageIconExample };
declare const ComboBoxMultipleSelectExample: () => JSX.Element;
export { ComboBoxMultipleSelectExample };
declare const ComboBoxStatusExample: () => JSX.Element;
export { ComboBoxStatusExample };
declare const ComboBoxVirtualizedExample: () => JSX.Element;
export { ComboBoxVirtualizedExample };
declare const DatePickerMainExample: () => JSX.Element;
export { DatePickerMainExample };
declare const DatePickerMenuExample: () => JSX.Element;
export { DatePickerMenuExample };
declare const DatePickerBasicExample: () => JSX.Element;
export { DatePickerBasicExample };
declare const DatePickerWithTimeExample: () => JSX.Element;
export { DatePickerWithTimeExample };
declare const DatePickerWithCombinedTimeExample: () => JSX.Element;
export { DatePickerWithCombinedTimeExample };
declare const DatePickerDateRangeExample: () => JSX.Element;
export { DatePickerDateRangeExample };
declare const DatePickerWithYearExample: () => JSX.Element;
export { DatePickerWithYearExample };
declare const DatePickerLocalizedExample: () => JSX.Element;
export { DatePickerLocalizedExample };
declare const DatePickerDatesDisabledExample: () => JSX.Element;
export { DatePickerDatesDisabledExample };
declare const DialogDismissibleExample: () => JSX.Element;
export { DialogDismissibleExample };
declare const DialogDraggableExample: () => JSX.Element;
export { DialogDraggableExample };
declare const DialogFullPageExample: () => JSX.Element;
export { DialogFullPageExample };
declare const DialogMainExample: () => JSX.Element;
export { DialogMainExample };
declare const DialogModalExample: () => JSX.Element;
export { DialogModalExample };
declare const DialogNonDismissibleExample: () => JSX.Element;
export { DialogNonDismissibleExample };
declare const DialogPlacementExample: () => JSX.Element;
export { DialogPlacementExample };
declare const DropdownButtonMainExample: () => JSX.Element;
export { DropdownButtonMainExample };
declare const DropdownMenuMainExample: () => JSX.Element;
export { DropdownMenuMainExample };
declare const DropdownMenuBasicExample: () => JSX.Element;
export { DropdownMenuBasicExample };
declare const DropdownMenuIconExample: () => JSX.Element;
export { DropdownMenuIconExample };
declare const DropdownMenuBadgeExample: () => JSX.Element;
export { DropdownMenuBadgeExample };
declare const DropdownMenuSublabelExample: () => JSX.Element;
export { DropdownMenuSublabelExample };
declare const DropdownMenuSubmenuExample: () => JSX.Element;
export { DropdownMenuSubmenuExample };
declare const DropdownMenuSeparatorExample: () => JSX.Element;
export { DropdownMenuSeparatorExample };
declare const DropdownMenuContentExample: () => JSX.Element;
export { DropdownMenuContentExample };
declare const ExpandableBlockMainExample: () => JSX.Element;
export { ExpandableBlockMainExample };
declare const ExpandableBlockWithCaptionExample: () => JSX.Element;
export { ExpandableBlockWithCaptionExample };
declare const ExpandableBlockAccordionExample: () => JSX.Element;
export { ExpandableBlockAccordionExample };
declare const ExpandableBlockStatusExample: () => JSX.Element;
export { ExpandableBlockStatusExample };
declare const ExpandableBlockSmallExample: () => JSX.Element;
export { ExpandableBlockSmallExample };
declare const ExpandableBlockBorderlessExample: () => JSX.Element;
export { ExpandableBlockBorderlessExample };
declare const ExpandableBlockFormExample: () => JSX.Element;
export { ExpandableBlockFormExample };
declare const ExpandableBlockDisabledExample: () => JSX.Element;
export { ExpandableBlockDisabledExample };
declare const FieldsetMainExample: () => JSX.Element;
export { FieldsetMainExample };
declare const FieldsetDisabledExample: () => JSX.Element;
export { FieldsetDisabledExample };
declare const FileUploadMainExample: () => JSX.Element;
export { FileUploadMainExample };
declare const FlexMainExample: () => JSX.Element;
export { FlexMainExample };
declare const FooterMainExample: () => JSX.Element;
export { FooterMainExample };
declare const HeaderMainExample: () => JSX.Element;
export { HeaderMainExample };
declare const InformationPanelMainExample: () => JSX.Element;
export { InformationPanelMainExample };
declare const InputGroupToggleSwitchExample: () => JSX.Element;
export { InputGroupToggleSwitchExample };
declare const InputGroupCheckboxGroupExample: () => JSX.Element;
export { InputGroupCheckboxGroupExample };
declare const InputGroupRadioGroupExample: () => JSX.Element;
export { InputGroupRadioGroupExample };
declare const InputMainExample: () => JSX.Element;
export { InputMainExample };
declare const InputSizesExample: () => JSX.Element;
export { InputSizesExample };
declare const InputSeparateLabelExample: () => JSX.Element;
export { InputSeparateLabelExample };
declare const InputInlineExample: () => JSX.Element;
export { InputInlineExample };
declare const InputStatusExample: () => JSX.Element;
export { InputStatusExample };
declare const InputButtonExample: () => JSX.Element;
export { InputButtonExample };
declare const KeyboardMainExample: () => JSX.Element;
export { KeyboardMainExample };
declare const LabelMainExample: () => JSX.Element;
export { LabelMainExample };
declare const ListMainExample: () => JSX.Element;
export { ListMainExample };
declare const ListSubcomponentsExample: () => JSX.Element;
export { ListSubcomponentsExample };
declare const ListLinksExample: () => JSX.Element;
export { ListLinksExample };
declare const ListComboboxExample: () => JSX.Element;
export { ListComboboxExample };
declare const NonIdealStateBadgatewayExample: () => JSX.Element;
export { NonIdealStateBadgatewayExample };
declare const NonIdealStateForbiddenExample: () => JSX.Element;
export { NonIdealStateForbiddenExample };
declare const NonIdealStateInternalErrorExample: () => JSX.Element;
export { NonIdealStateInternalErrorExample };
declare const NonIdealStatePagenotfoundExample: () => JSX.Element;
export { NonIdealStatePagenotfoundExample };
declare const NonIdealStateRedirectExample: () => JSX.Element;
export { NonIdealStateRedirectExample };
declare const NonIdealStateServiceunavailableExample: () => JSX.Element;
export { NonIdealStateServiceunavailableExample };
declare const NonIdealStateTimeoutExample: () => JSX.Element;
export { NonIdealStateTimeoutExample };
declare const NonIdealStateUnauthorizedExample: () => JSX.Element;
export { NonIdealStateUnauthorizedExample };
declare const NonIdealStateErrorExample: () => JSX.Element;
export { NonIdealStateErrorExample };
declare const ProgressLinearMainExample: () => JSX.Element;
export { ProgressLinearMainExample };
declare const ProgressRadialMainExample: () => JSX.Element;
export { ProgressRadialMainExample };
declare const RadioMainExample: () => JSX.Element;
export { RadioMainExample };
declare const RadioStatusesExample: () => JSX.Element;
export { RadioStatusesExample };
declare const RadioTileMainExample: () => JSX.Element;
export { RadioTileMainExample };
declare const RadioTileColorExample: () => JSX.Element;
export { RadioTileColorExample };
declare const SearchBoxMainExample: () => JSX.Element;
export { SearchBoxMainExample };
declare const SearchBoxBasicExample: () => JSX.Element;
export { SearchBoxBasicExample };
declare const SearchBoxSizeExample: () => JSX.Element;
export { SearchBoxSizeExample };
declare const SearchBoxExpandableExample: () => JSX.Element;
export { SearchBoxExpandableExample };
declare const SearchBoxStatusExample: () => JSX.Element;
export { SearchBoxStatusExample };
declare const SearchBoxCustomExample: () => JSX.Element;
export { SearchBoxCustomExample };
declare const SearchBoxCustomOpenExample: () => JSX.Element;
export { SearchBoxCustomOpenExample };
declare const SelectDisableExample: () => JSX.Element;
export { SelectDisableExample };
declare const SelectIconExample: () => JSX.Element;
export { SelectIconExample };
declare const SelectMainExample: () => JSX.Element;
export { SelectMainExample };
declare const SelectStatusesExample: () => JSX.Element;
export { SelectStatusesExample };
declare const SelectSublabelsExample: () => JSX.Element;
export { SelectSublabelsExample };
declare const SelectTruncateExample: () => JSX.Element;
export { SelectTruncateExample };
declare const SideNavigationMainExample: () => JSX.Element;
export { SideNavigationMainExample };
declare const SideNavigationBasicExample: () => JSX.Element;
export { SideNavigationBasicExample };
declare const SideNavigationActiveItemExample: () => JSX.Element;
export { SideNavigationActiveItemExample };
declare const SideNavigationSubmenuExample: () => JSX.Element;
export { SideNavigationSubmenuExample };
declare const SliderMainExample: () => JSX.Element;
export { SliderMainExample };
declare const SliderRangeExample: () => JSX.Element;
export { SliderRangeExample };
declare const SliderRangeMultipleExample: () => JSX.Element;
export { SliderRangeMultipleExample };
declare const SliderVerticalExample: () => JSX.Element;
export { SliderVerticalExample };
declare const SliderLabelsExample: () => JSX.Element;
export { SliderLabelsExample };
declare const SliderThumbCustomExample: () => JSX.Element;
export { SliderThumbCustomExample };
declare const SliderTooltipCustomExample: () => JSX.Element;
export { SliderTooltipCustomExample };
declare const SliderTooltipNoneExample: () => JSX.Element;
export { SliderTooltipNoneExample };
declare const StepperMainExample: () => JSX.Element;
export { StepperMainExample };
declare const StepperShortExample: () => JSX.Element;
export { StepperShortExample };
declare const StepperLongExample: () => JSX.Element;
export { StepperLongExample };
declare const StepperTooltipExample: () => JSX.Element;
export { StepperTooltipExample };
declare const StepperLocalizationExample: () => JSX.Element;
export { StepperLocalizationExample };
declare const StepperLayoutExample: () => JSX.Element;
export { StepperLayoutExample };
declare const SurfaceMainExample: () => JSX.Element;
export { SurfaceMainExample };
declare const SurfaceElevationExample: () => JSX.Element;
export { SurfaceElevationExample };
declare const SurfaceHeaderFooterExample: () => JSX.Element;
export { SurfaceHeaderFooterExample };
declare const SurfaceNoPaddingExample: () => JSX.Element;
export { SurfaceNoPaddingExample };
declare const TableMainExample: () => JSX.Element;
export { TableMainExample };
declare const TabsMainExample: () => JSX.Element;
export { TabsMainExample };
declare const TabsOverflowExample: () => JSX.Element;
export { TabsOverflowExample };
declare const TagMainExample: () => JSX.Element;
export { TagMainExample };
declare const TagBasicExample: () => JSX.Element;
export { TagBasicExample };
declare const TagDefaultExample: () => JSX.Element;
export { TagDefaultExample };
declare const TagContainerMainExample: () => JSX.Element;
export { TagContainerMainExample };
declare const TagContainerWrapExample: () => JSX.Element;
export { TagContainerWrapExample };
declare const TagContainerTruncateExample: () => JSX.Element;
export { TagContainerTruncateExample };
declare const TagContainerScrollExample: () => JSX.Element;
export { TagContainerScrollExample };
declare const TextareaMainExample: () => JSX.Element;
export { TextareaMainExample };
declare const TextareaScrollExample: () => JSX.Element;
export { TextareaScrollExample };
declare const TextareaStatusExample: () => JSX.Element;
export { TextareaStatusExample };
declare const TextareaInlineExample: () => JSX.Element;
export { TextareaInlineExample };
declare const TextMainExample: () => JSX.Element;
export { TextMainExample };
declare const TileMainExample: () => JSX.Element;
export { TileMainExample };
declare const ToastMainExample: () => JSX.Element;
export { ToastMainExample };
declare const ToggleSwitchMainExample: () => JSX.Element;
export { ToggleSwitchMainExample };
declare const ToggleSwitchSizesExample: () => JSX.Element;
export { ToggleSwitchSizesExample };
declare const ToggleSwitchLabelsExample: () => JSX.Element;
export { ToggleSwitchLabelsExample };
declare const ToggleSwitchIconExample: () => JSX.Element;
export { ToggleSwitchIconExample };
declare const ToggleSwitchInputGroupExample: () => JSX.Element;
export { ToggleSwitchInputGroupExample };
declare const TooltipMainExample: () => JSX.Element;
export { TooltipMainExample };
declare const TooltipPlacementExample: () => JSX.Element;
export { TooltipPlacementExample };
declare const TransferListMainExample: () => JSX.Element;
export { TransferListMainExample };
declare const TransferListWithLabelExample: () => JSX.Element;
export { TransferListWithLabelExample };
declare const TreeMainExample: () => JSX.Element;
export { TreeMainExample };
declare const VisuallyHiddenIconExample: () => JSX.Element;
export { VisuallyHiddenIconExample };
declare const VisuallyHiddenMoreTextExample: () => JSX.Element;
export { VisuallyHiddenMoreTextExample };
