name: 🐛 Bug
description: Create a bug report to help us improve
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to iTwinUI by creating an issue!
        Make sure you first do a search for existing issues so that this is is not a duplicate.
        Also visit our [FAQ](https://github.com/iTwin/iTwinUI/wiki/FAQ)
  - type: textarea
    attributes:
      label: Describe the bug (current behavior)
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction
      description: 'Fork this sandbox: https://stackblitz.io/github/iTwin/iTwinUI/tree/main/minimal-sandbox?file=/src/App.tsx'
      placeholder: 'Link to a minimal repro:'
  - type: input
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Fill this out
        2. Fill this out
        3. Fill this out
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: Add anything else you want to mention (package version, environment info, possible solution, etc)
    validations:
      required: false
