name: PR
on:
  pull_request:

jobs:
  assign-author:
    name: Assign PR author
    runs-on: ubuntu-latest

    steps:
      - name: Assign author using github-script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.actor]
            })
